includes("../include.lua")
add_rules("mode.debug", "mode.release")
set_defaultmode("debug")
set_plat("windows")
set_arch("x86")
set_toolchains("clang-cl")
set_languages("c17", "cxx23")
set_config("nomtd", true)

set_runtimes("MT")
set_policy("build.optimization.lto", is_mode("release"))
add_repositories("EdgeMinHook ../EdgeMinHook/build")
add_requires("edgeminhook", {plat = "windows", arch = "x86"})

target("Bluehill's Loader")
    add_rules("asi")
    add_files("src/dllmain.cpp", "src/global.cppm", "src/functions.cppm", "src/bonus.cppm", "src/level.cppm", "src/music.cppm", "src/fontbin.cppm", "src/textloc.cppm", "src/EdgeMinHook.cppm")
    add_packages("edgeminhook")
